/* Strategy provided by p6-XML-LibXML:author<FROGGS> */
#ifdef _WIN32
#define DLLEXPORT __declspec(dllexport)
#else
#define DLLEXPORT extern
#endif

#include <goocanvas.h>

#define s(name)     DLLEXPORT int sizeof_ ## name () { return sizeof(name); }

s(GooCanvas)
s(GooCanvasBounds)
s(GooCanvasClass)
s(GooCanvasEllipse)
s(GooCanvasEllipseClass)
s(GooCanvasEllipseData)
s(GooCanvasEllipseModel)
s(GooCanvasEllipseModelClass)
s(GooCanvasGrid)
s(GooCanvasGridClass)
s(GooCanvasGridData)
s(GooCanvasGridModel)
s(GooCanvasGridModelClass)
s(GooCanvasGroup)
s(GooCanvasGroupClass)
s(GooCanvasGroupModel)
s(GooCanvasGroupModelClass)
s(GooCanvasImage)
s(GooCanvasImageClass)
s(GooCanvasImageData)
s(GooCanvasImageModel)
s(GooCanvasImageModelClass)
s(GooCanvasItemIface)
s(GooCanvasItemModelIface)
s(GooCanvasItemModelSimple)
s(GooCanvasItemModelSimpleClass)
s(GooCanvasItemSimple)
s(GooCanvasItemSimpleClass)
s(GooCanvasItemSimpleData)
s(GooCanvasLineDash)
s(GooCanvasPath)
s(GooCanvasPathClass)
s(GooCanvasPathData)
s(GooCanvasPathModel)
s(GooCanvasPathModelClass)
s(GooCanvasPoints)
s(GooCanvasPolyline)
s(GooCanvasPolylineArrowData)
s(GooCanvasPolylineClass)
s(GooCanvasPolylineData)
s(GooCanvasPolylineModel)
s(GooCanvasPolylineModelClass)
s(GooCanvasRect)
s(GooCanvasRectClass)
s(GooCanvasRectData)
s(GooCanvasRectModel)
s(GooCanvasRectModelClass)
s(GooCanvasStyle)
s(GooCanvasStyleClass)
s(GooCanvasStyleProperty)
s(GooCanvasTable)
s(GooCanvasTableClass)
s(GooCanvasTableData)
s(GooCanvasTableDimension)
s(GooCanvasTableModel)
s(GooCanvasTableModelClass)
s(GooCanvasText)
s(GooCanvasTextClass)
s(GooCanvasTextData)
s(GooCanvasTextModel)
s(GooCanvasTextModelClass)
s(GooCanvasWidget)
s(GooCanvasWidgetClass)
